"""modify User

Revision ID: 632c83625fdd
Revises: 7c0253b873ff
Create Date: 2018-01-02 17:07:53.768054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632c83625fdd'
down_revision = '7c0253b873ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
